<?php
/*	
+-----------------------------------------------------------------------------------+
| Copyright (c) 2013, Nils Dšhring												|
| All rights reserved.																|
| Author: Nils Dšhring <nils.doehring@gmail.com>								|
+-----------------------------------------------------------------------------------+ 
*/
/**
 * @see: http://framework.zend.com/manual/1.12/en/zend.loader.pluginloader.html#zend.loader.pluginloader.performance.example
 * 
 * @author nils.doehring 
 */
//manually-generated by Rockdot
include_once 'Rockdot/Loader.php';
include_once 'Rockdot/Http/Cookie.php';
include_once 'Rockdot/Http/Request.php';
include_once 'Rockdot/Http/Uri.php';
include_once 'Rockdot/Data.php';
include_once 'Rockdot/Config.php';
include_once 'Rockdot/Zend/Plugin/LoginStatus.php';
include_once 'Rockdot/Zend/Plugin/RewriteIp.php';
include_once 'Rockdot/Zend/Plugin/SslSwitch.php';
include_once 'Rockdot/Zend/Plugin/DetectMobile.php';
include_once 'Rockdot/Zend/Plugin/Maintenance.php';
include_once 'Rockdot/Zend/View/Helper/Page.php';
include_once 'Rockdot/Zend/View/Helper/FormText.php';
include_once 'Rockdot/Zend/View/Helper/Script.php';
//auto-generated by Zend
include_once 'Zend/Controller/Action/Helper/ViewRenderer.php';
include_once 'Zend/View/Helper/Navigation.php';
include_once 'Zend/View/Helper/Doctype.php';
include_once 'Zend/View/Helper/HeadMeta.php';
include_once 'Zend/View/Helper/HeadTitle.php';
include_once 'Zend/Filter/Word/CamelCaseToDash.php';
include_once 'Zend/Filter/StringToLower.php';
include_once 'Zend/View/Helper/HeadLink.php';
include_once 'Zend/View/Helper/Layout.php';
include_once 'Zend/Controller/Action/Helper/FlashMessenger.php';
include_once 'Zend/Controller/Action/Helper/Url.php';
include_once 'Zend/Form/Decorator/FormElements.php';
include_once 'Zend/Form/Decorator/Form.php';
include_once 'Zend/Form/Decorator/ViewHelper.php';
include_once 'Zend/View/Helper/FormSelect.php';
include_once 'Zend/View/Helper/Form.php';
include_once 'Zend/Paginator/ScrollingStyle/Elastic.php';
include_once 'Zend/View/Helper/Partial.php';
include_once 'Zend/Controller/Action/Helper/Redirector.php';
include_once 'Zend/View/Helper/FormPassword.php';
include_once 'Zend/View/Helper/FormSubmit.php';
include_once 'Zend/Validate/File/Upload.php';
include_once 'Zend/Validate/File/Count.php';
include_once 'Zend/Validate/File/Size.php';
include_once 'Zend/Validate/File/Extension.php';
include_once 'Zend/Validate/File/IsImage.php';
include_once 'Zend/Filter/File/Rename.php';
include_once 'Zend/Controller/Action/Helper/Json.php';
include_once 'Zend/Validate/NotEmpty.php';
include_once 'Zend/Application/Resource/Layout.php';
include_once 'Zend/Application/Resource/View.php';
include_once 'Zend/View/Helper/BaseUrl.php';
include_once 'Zend/Form/Decorator/Label.php';
include_once 'Zend/View/Helper/FormLabel.php';